---
title: "Data visualization"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Student's Sleep Data
### Description
Data which show the effect of two soporific drugs (increase in hours of sleep compared to control) on 10 patients.
```markdown
Format
A data frame with 20 observations on 3 variables.

[, 1]	extra	numeric	increase in hours of sleep
[, 2]	group	factor	drug given
[, 3]	ID	factor	patient ID
```

```
 extra group ID
1    0.7     1  1
2   -1.6     1  2
3   -0.2     1  3
4   -1.2     1  4
5   -0.1     1  5
6    3.4     1  6
7    3.7     1  7
8    0.8     1  8
9    0.0     1  9
10   2.0     1 10
11   1.9     2  1
12   0.8     2  2
13   1.1     2  3
14   0.1     2  4
15  -0.1     2  5
16   4.4     2  6
17   5.5     2  7
18   1.6     2  8
19   4.6     2  9
20   3.4     2 10
```
## bar plot
### compare the extra sleep time of two groups
### It is obvious that the soporific drug group2 used are more effective
```{R}
library(ggplot2)
s1 <- sleep[1:10, 1:3]
ggplot(s1, aes(x = ID , y = extra)) + geom_col(fill = "pink", color = "black")
s2 <- sleep[11:20, 1:3]
ggplot(s2, aes(x = ID , y = extra)) + geom_col(fill = "indianred", color = "black")
```

## box plot 
### mean of extra sleep time in group1 is around 0.3hr while in group 2 is almost 2 hr
```{r}
library(ggplot2)
ggplot(sleep, aes(x = group, y = extra)) + geom_boxplot()
```

## scatter 
```{r}
ggplot(sleep, aes(x = ID , y = extra, color = group)) + geom_point()
```

```{r}
library(ggplot2)
ggplot(sleep, aes(x = group , y = extra, color = ID)) + geom_point()
```

## histograms
```{r}
qplot(extra, data = sleep, fill = group)
```

```{r}
ggplot(sleep, aes(x = extra)) + geom_histogram()
```

```{r}
library(ggplot2)
ggplot(sleep, aes(x = group)) +
geom_bar(fill = "lightblue", colour = "black")
```