---
title: "intermediate R3"
output: html_document
---
#Introduction to Functions
* create list : list()
* display a variable : print ()
* 求標準差 : sd()
* useful tricks :　
  > arg(sd)
  function (x, na.rm = FALSE)
  NULL

> help(sample)
>
> ?sample
>
> args(sample)

Check the documentation on the mean() function 
> ?mean

>mean(x, ...)
>mean(x, trim = 0, na.rm = FALSE, ...)
>
>The ... is called the ellipsis. It is a way for R to pass arguments along without the function having to name them explicitly. The ellipsis will be treated in more detail in future courses.

```
# The linkedin and facebook vectors have already been created for you
> linkedin <- c(16, 9, 13, 5, 2, 17, 14)
> facebook <- c(17, 7, 5, 16, 8, 13, 14)
> 
> # Calculate the mean of the sum
> avg_sum <- mean(linkedin + facebook)
> 
> # Calculate the trimmed mean of the sum
> avg_sum_trimmed <- mean(linkedin + facebook, trim = 0.2)
> 
> # Inspect both new variables
> avg_sum
[1] 22.2857
> avg_sum_trimmed
[1] 22.6
```
```
> # The linkedin and facebook vectors have already been created for you
> linkedin <- c(16, 9, 13, 5, NA, 17, 14)
> facebook <- c(17, NA, 5, 16, 8, 13, 14)
> 
> # Basic average of linkedin
> mean (linkedin)
[1] NA
> 
> # Advanced average of linkedin
> mean (linkedin,trim = 0, na.rm = TRUE )
[1] 12.33333
```
```
# The linkedin and facebook vectors have already been created for you
> linkedin <- c(16, 9, 13, 5, NA, 17, 14)
> facebook <- c(17, NA, 5, 16, 8, 13, 14)
> 
> # Calculate the mean absolute deviation
> mean(abs(linkedin - facebook), na.rm = TRUE)
[1] 4.8
```
> mean(x, trim = 0, na.rm = FALSE, ...)
>
>x is required; if you do not specify it, R will throw an error. trim and na.rm are optional arguments: they have a default value which is used if the arguments are not explicitly specified.

#<font color="orange">writing functions<font>
> my_fun <- function(arg1, arg2) {
  body
}

```
# Create a function pow_two()
> pow_two <- function(x) {
    x ^ 2
  }
> 
> # Use the function
> pow_two(12)
[1] 144
> 
> # Create a function sum_abs()
> sum_abs <- function(x, y) {
    abs(x) + abs(y)
  }
> 
> # Use the function
> sum_abs(-2, 3)
[1] 5
```
```
# Define the function hello()
> hello <- function() {
    print("Hi there!")
    TRUE
  }
> 
> # Call the function hello()
> hello()
[1] "Hi there!"
[1] TRUE
```
```
 # Finish the pow_two() function
> pow_two <- function(x, print_info = TRUE) {
    y <- x ^ 2
    if (print_info) {
      print(paste(x, "to the power two equals", y))
    }
    return(y)
  }
> 
> # Some calls of the pow_two() function
> pow_two(5)
[1] "5 to the power two equals 25"
[1] 25
> pow_two(5, FALSE)
[1] 25
> pow_two(5, TRUE)
[1] "5 to the power two equals 25"
[1] 25
```
```
 # The linkedin and facebook vectors have already been created for you
> linkedin
[1] 16  9 13  5  2 17 14
> facebook
[1] 17  7  5 16  8 13 14
 
> # Define the interpret function
> interpret <- function(num_views) {
    if (num_views > 15) {
  print("You're popular!")
   return(num_views)
  }
   else { print("Try to be more visible!")}
    return(0)
   }

> # Call the interpret function twice
> interpret(linkedin[1])
[1] "You're popular!"
[1] 16
>  interpret(facebook[2])
[1] "Try to be more visible!"
[1] 0
```
```
# Define the interpret_all() function
> # views: vector with data to interpret
> # return_sum: return total number of views on popular days?
> interpret_all <- function(views, return_sum = TRUE) {
    count <- 0
  
    for (v in views) {
      count <- count + interpret(v)
    }
  
    if (return_sum) {
      return(count)
    } else {
      return(NULL)
    }
  }
> 
> # Call the interpret_all() function on both linkedin and facebook
> interpret_all(linkedin)
[1] "You're popular!"
[1] "Try to be more visible!"
[1] "Try to be more visible!"
[1] "Try to be more visible!"
[1] "Try to be more visible!"
[1] "You're popular!"
[1] "Try to be more visible!"
[1] 33
> interpret_all(facebook)
[1] "You're popular!"
[1] "Try to be more visible!"
[1] "Try to be more visible!"
[1] "You're popular!"
[1] "Try to be more visible!"
[1] "Try to be more visible!"
[1] "Try to be more visible!"
[1] 33
```
#<font color="orange"> R packages <font>
> install packages : install.packages()
> load packages : library() , require()
> load packages = attach package to search list

```
# Load the ggplot2 package
> library("ggplot2")
> 
> # Retry the qplot() function
> qplot(mtcars$wt, mtcars$hp)
> 
> # Check out the currently attached packages again
> search()
 [1] ".GlobalEnv"        "package:ggplot2"   "package:RBackend" 
 [4] "package:stats"     "package:graphics"  "package:grDevices"
 [7] "package:utils"     "package:datasets"  "package:methods"  
[10] "Autoloads"         "package:base"
```