---
title: "Taiwan_map+ggplot"
output: html_document
---
# Practice using ggplot and ggmap

# bookstore[](http://myinsuranceshark.com/wp-content/uploads/2016/09/books-3.jpg){width=10%}

```{r}
library(readr)

bs <- read_csv("book.csv")

lon.deg <- sapply((strsplit(as.character(bs$"經度"), ",")), as.numeric)
lat.deg <- sapply((strsplit(as.character(bs$"緯度"), ",")), as.numeric)
bs$lat <- lat.deg
bs$lon <- lon.deg

library(ggmap)
map_4 <- get_map(location = c(lon = 120.5, lat = 23.625), zoom = 8)
ggmap(map_4) + geom_point(aes(x = lon, y = lat), data = bs)

```


```{r}
library(readr)

bs <- read_csv("book.csv")

lon.deg <- sapply((strsplit(as.character(bs$"經度"), ",")), as.numeric)
lat.deg <- sapply((strsplit(as.character(bs$"緯度"), ",")), as.numeric)
bs$lat <- lat.deg
bs$lon <- lon.deg

library(ggmap)
map_4 <- get_map(location = c(lon = 120.5, lat = 23.625), zoom = 8)
ggmap(map_4) + geom_point(aes(x = lon, y = lat), data = bs)

```


```{r}
ggmap(map_4, darken = c(0.5, "white")) +
  geom_point(aes(x = lon, y = lat), data = bs)
```


```{r}
library(readr)

bs <- read_csv("book.csv")

lon.deg <- sapply((strsplit(as.character(bs$"經度"), ",")), as.numeric)
lat.deg <- sapply((strsplit(as.character(bs$"緯度"), ",")), as.numeric)
bs$lat <- lat.deg
bs$lon <- lon.deg

library(ggmap)
map_5 <- get_map(location = c(lon = 121.576957, lat = 25.028702), zoom = 15)
ggmap(map_5) + geom_point(aes(x = lon, y = lat), data = bs)

```


```{r}
library(readr)

bs <- read_csv("book.csv")

lon.deg <- sapply((strsplit(as.character(bs$"經度"), ",")), as.numeric)
lat.deg <- sapply((strsplit(as.character(bs$"緯度"), ",")), as.numeric)
bs$lat <- lat.deg
bs$lon <- lon.deg

library(ggmap)
map_6 <- get_map(location = c(lon = 121.519872, lat =25.042141), zoom = 13)
ggmap(map_6) + geom_point(aes(x = lon, y = lat), data = bs)

```


```{r}
library(readr)

bs <- read_csv("book.csv")

lon.deg <- sapply((strsplit(as.character(bs$"經度"), ",")), as.numeric)
lat.deg <- sapply((strsplit(as.character(bs$"緯度"), ",")), as.numeric)
bs$lat <- lat.deg
bs$lon <- lon.deg

library(ggmap)
map_5 <- get_map(location = c(lon = 121.542709, lat = 25.026158), zoom = 15)
ggmap(map_5) + geom_point(aes(x = lon, y = lat), data = bs)

```

```{r}
library(readr)

bs <- read_csv("book.csv")

lon.deg <- sapply((strsplit(as.character(bs$"經度"), ",")), as.numeric)
lat.deg <- sapply((strsplit(as.character(bs$"緯度"), ",")), as.numeric)
bs$lat <- lat.deg
bs$lon <- lon.deg

library(ggmap)
map_6 <- get_map(location = c(lon = 120.673648, lat =24.147736), zoom = 14)
ggmap(map_6) + geom_point(aes(x = lon, y = lat), data = bs)

```






