
rm(list=ls(all.names = TRUE))
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))

toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "看")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "阿")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "只")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "自己")
docs <- tm_map(docs, toSpace, "知道")
docs <- tm_map(docs, toSpace, "還")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "之")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "啊")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "讓")
docs <- tm_map(docs, toSpace, "像")
docs <- tm_map(docs, toSpace, "這樣")
docs <- tm_map(docs, toSpace, "[a-z]")
docs <- tm_map(docs, toSpace, "EAseries")
docs <- tm_map(docs, toSpace, "NA")
docs <- tm_map(docs, toSpace, "pttcc")
docs <- tm_map(docs, toSpace, "From")
docs <- tm_map(docs, toSpace, "for")
docs <- tm_map(docs, toSpace, "the")
docs <- tm_map(docs, toSpace, "XD")
docs <- tm_map(docs, toSpace, "The")
docs <- tm_map(docs, toSpace, "妳")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "標題")
docs <- tm_map(docs, toSpace, "已經")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "她")
docs <- tm_map(docs, toSpace, "他")
docs <- tm_map(docs, toSpace, "把")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "a")
docs <- tm_map(docs, toSpace, "Re")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "m")
docs <- tm_map(docs, toSpace, "n")
docs <- tm_map(docs, toSpace, "s")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "很")
docs <- tm_map(docs, toSpace, "們")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "A")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace, "可")
docs <- tm_map(docs, toSpace, "上")
docs <- tm_map(docs, toSpace, "來")
docs <- tm_map(docs, toSpace, "為")
docs <- tm_map(docs, toSpace, "又")
docs <- tm_map(docs, toSpace, "想")
docs <- tm_map(docs, toSpace, "過")
docs <- tm_map(docs, toSpace, "所以")
docs <- tm_map(docs, toSpace, "因")
docs <- tm_map(docs, toSpace, "才")
docs <- tm_map(docs, toSpace, "那")
docs <- tm_map(docs, toSpace, "個")
docs <- tm_map(docs, toSpace, "這")
docs <- tm_map(docs, toSpace, "[A-Z]")
docs <- tm_map(docs, toSpace, "應該")
docs <- tm_map(docs, toSpace, "去")
docs <- tm_map(docs, toSpace, "說")
docs <- tm_map(docs, toSpace, "一")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "些")
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "所")
docs <- tm_map(docs, toSpace, "以")
docs <- tm_map(docs, toSpace, "其實")
docs <- tm_map(docs, toSpace, "能")
docs <- tm_map(docs, toSpace, "編輯")
docs <- tm_map(docs, toSpace, "被")
docs <- tm_map(docs, toSpace, "和")
docs <- tm_map(docs, toSpace, "對")
docs <- tm_map(docs, toSpace, "內")
docs <- tm_map(docs, toSpace, "多")
docs <- tm_map(docs, toSpace, "與")
docs <- tm_map(docs, toSpace, "而")
docs <- tm_map(docs, toSpace, "或")
docs <- tm_map(docs, toSpace, "呢")
docs <- tm_map(docs, toSpace, "麼")
docs <- tm_map(docs, toSpace, "然後")
docs <- tm_map(docs, toSpace, "啦")
docs <- tm_map(docs, toSpace, "裡")
docs <- tm_map(docs, toSpace, "怎")
docs <- tm_map(docs, toSpace, "更")
docs <- tm_map(docs, toSpace, "再")
docs <- tm_map(docs, toSpace, "已")
docs <- tm_map(docs, toSpace, "次")
docs <- tm_map(docs, toSpace, "如果")
docs <- tm_map(docs, toSpace, "每")
docs <- tm_map(docs, toSpace, "卻")
docs <- tm_map(docs, toSpace, "喔")
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs

mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")

wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(4,0.1),min.freq=64,max.words=Inf,
          random.order=TRUE, random.color=FALSE, 
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)


          
